### ISSUE TITLE
Weird thing about Cookie Clicker

### ISSUE THREAD

**Issue by Matocolotoe** [NiklasEi/cookieclicker-for-gamebox#13]
Are `data.yml` and `saves.yml` synchronized regarding the amount of total cookies per player ?
Because when the server reboots and some of the cookies haven't been saved, the total amount of cookies in the top list increases but not for the player

**Comment by NiklasEi** [comment]
They should have the same values. The value is written to both files whenever the game is closed. The game will always be closed for a normal server shutdown/reboot.
They are not actively syncronized though.

Are you comparing the amount in the inventory title with the top list, or really the entries in the files?

**Comment by Matocolotoe** [comment]
I'm comparing the amount in the in-game GUIs

**Comment by NiklasEi** [comment]
If I understood correctly, the top list had the right amount, but the player was missing cookies. The first is done in GameBox, the second in Cookieclicker. So I transferred the issue (also I wanted to test that Beta feature ^^).

I went over the code that should be triggered on a reboot, but couldn't find a problem. Most things that could go wrong should throw an error in the console. You can take a look yourself:

1. "onDisable" of the game gets called: https://github.com/NiklasEi/cookieclicker-for-gamebox/blob/master/src/main/java/me/nikl/cookieclicker/CookieClicker.java#L164-L167
2. The game manager quits and saves all games to the database (sync, because the server is shutting down): https://github.com/NiklasEi/cookieclicker-for-gamebox/blob/master/src/main/java/me/nikl/cookieclicker/CCGameManager.java#L117
3. The database is saved (looking at the file implementation here, because you mentioned `saves.yml`). Also sync because of the shutdown: https://github.com/NiklasEi/cookieclicker-for-gamebox/blob/master/src/main/java/me/nikl/cookieclicker/data/FileDatabase.java#L96

When I reboot my server the file is written to.

Sorry, without a stack trace or steps to reproduce I can't do more here.
