### ISSUE TITLE
Full Translation.

### ISSUE THREAD

**Issue by TheIntelloBox** [NiklasEi/cookieclicker-for-gamebox#2]

**Comment by NiklasEi** [comment]
@TheIntelloBox If you would like to contribute the french language file, you can already start translating with the current english language file. The buildings section is done and for the upgrades Cursor and Grandma are complete at the time of writing this.

**Comment by TheIntelloBox** [comment]
I already translated all the file for all your plugins.

**Comment by NiklasEi** [comment]
You allready finished translating [the new buildings and upgrades section](https://github.com/NiklasEi/GameBox_CookieClicker/blob/master/language/lang_en.yml#L38)?
I'll add the rest of the upgrades in the next days, then full language suport is done and CookieClicker will leave beta.

This will be the biggest language file I did until now because of all the different buildings and upgrades.

**Comment by TheIntelloBox** [comment]
Fantastic. :D I hope this will be Sunday. :D

**Comment by NiklasEi** [comment]
All buildings and upgrades that are currently in the game have full language support now :)

**Comment by TheIntelloBox** [comment]
When is the update ? :D

**Comment by NiklasEi** [comment]
I'll clean up and upload the new version on Spigot tmr.
